# Generated by Django 2.2.3 on 2019-07-09 08:45

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NavigationItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('url', models.CharField(help_text='Веедите слово в виде about/', max_length=255, unique=True, verbose_name='URL')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('app', models.CharField(choices=[('redirect', 'Redirect'), ('page', 'Простая страница'), ('vacancies', 'Вакансии'), ('test', 'Тестовое приложение')], default='page', help_text='Выберите приложение для страницы', max_length=50, verbose_name='Тип страницы')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Содержание')),
                ('is_protected', models.BooleanField(default=False, verbose_name='Защитить паролем')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='navigation.NavigationItem')),
            ],
            options={
                'verbose_name': 'Страница сайта',
                'verbose_name_plural': 'Страницы сайта',
            },
        ),
    ]
