# Generated by Django 2.2.3 on 2019-07-09 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigationitem',
            name='to_homepage',
            field=models.BooleanField(default=False, verbose_name='Отображать контент на главной?'),
        ),
    ]
