# Generated by Django 2.2.3 on 2019-07-10 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0002_navigationitem_to_homepage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigationitem',
            name='app',
            field=models.CharField(choices=[('redirect', 'Redirect'), ('pages', 'Простая страница'), ('jobs', 'Вакансии'), ('test', 'Тестовое приложение')], default='page', help_text='Выберите приложение для страницы', max_length=50, verbose_name='Тип страницы'),
        ),
    ]
