# Generated by Django 2.2.3 on 2019-07-10 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('title', models.CharField(max_length=255, verbose_name='Название вакансии')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
            },
        ),
        migrations.CreateModel(
            name='Responsibility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('title', models.CharField(max_length=255, verbose_name='Название вакансии')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsibilities', to='jobs.Job')),
            ],
            options={
                'verbose_name': 'Вакансии Ожидание',
                'verbose_name_plural': 'Вакансии Ожидания',
            },
        ),
        migrations.CreateModel(
            name='Expectation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('title', models.CharField(max_length=255, verbose_name='Название вакансии')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expectations', to='jobs.Job')),
            ],
            options={
                'verbose_name': 'Вакансии Ожидание',
                'verbose_name_plural': 'Вакансии Ожидания',
            },
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('title', models.CharField(max_length=255, verbose_name='Название вакансии')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='jobs.Job')),
            ],
            options={
                'verbose_name': 'Вакансии Ожидание',
                'verbose_name_plural': 'Вакансии Ожидания',
            },
        ),
    ]
