# Generated by Django 2.2.3 on 2019-07-10 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='condition',
            options={'verbose_name': 'Условия', 'verbose_name_plural': 'Условия'},
        ),
        migrations.AlterModelOptions(
            name='expectation',
            options={'verbose_name': 'Мы ожидаем', 'verbose_name_plural': 'Мы ожидаем'},
        ),
        migrations.AlterModelOptions(
            name='responsibility',
            options={'verbose_name': 'Функции и обязанности', 'verbose_name_plural': 'Функции и обязанности'},
        ),
        migrations.RemoveField(
            model_name='responsibility',
            name='title',
        ),
    ]
