# Generated by Django 2.2.3 on 2019-07-10 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20190710_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsibility',
            name='title',
            field=models.CharField(default='d', max_length=255, verbose_name='Функции и обязанности'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='condition',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Условия'),
        ),
        migrations.AlterField(
            model_name='expectation',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Мы ожидаем'),
        ),
    ]
